baseURL = "/"
languageCode = "en-us"
title = "Opposable Thumbs"
theme = "mainroad"

[permalinks]
	posts = "/posts/:year/:month/:slug/"

[Author]
	name = "Thomas Lockney"

[Params]
	subtitle = "Are we not men?"
	copyright = "Thomas Lockney"
	twitter_cards = true
	# authorbox = true
	post_meta = ["date", "categories", "translations"]
	post_navigation = true	

[Params.sidebar]
	home = "right"
	list = "right"
	single = false
	widgets = ["recent", "social", "sidemenu"]

[Params.widgets.social]
	twitter = "tlockney"
	linkedin = "thomaslockney"
	instagram = "tlockney"
	github = "tlockney"

[[menu.main]]
	identifier = "blog"
	name = "Blog"
	url = "/posts"
	weight = 100

[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about"
	weight = 100

[[menu.main]]
	identifier = "notes"
	name = "Notes"
	url = "/notes"
	weight = 100
