baseURL = "/"
languageCode = "en-us"
title = "Opposable Thumbs"
theme = "whiteplain"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"
copyright = "&copy; Copyright 2020 Thomas Lockney"

[permalinks]
	posts = "/posts/:year/:month/:slug/"

[Author]
	name = "Thomas Lockney"

[params.author]
	name = "Thomas Lockney"
	gravatar = "thomas@lockney.net"
	twitter = "tlockney"
	linkedin = "thomaslockney"
	instagram = "tlockney"
	github = "tlockney"
	medium = "tlockney"
	youtube = "ThomasLockney"
	email = "thomas@lockney.net"
	facebook = "tlockney"
	mastodon = "fosstodon/@tlockney"

[[menu.main]]
	identifier = "blog"
	name = "Blog"
	url = "/posts"
	weight = 100
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about"
	weight = 100
#[[menu.main]]
#	identifier = "notes"
#	name = "Notes"
#	url = "/notes"
#	weight = 100
